### ISSUE TITLE
Next step with GPU

### ISSUE THREAD

**Issue by bgnt44** [kaschmo/sh_face_rec#13]
Hi, first thing amazing work, both code and wiki are very detailed and easy to follow, solution was up and running in a breeze !
im running dlib , tf and opencv with cuda support with a 1080gtx and i would like to know if you have suggestion for models with better accuracy and detection ability, especially with bad source frame like security cam (often quite blurry faces)

**Comment by kaschmo** [comment]
Thank you.
Sorry. I cannot help with recommendations for such models. Though I have to say that performance on my 640x480 cams where faces are usually only 40x40 and blurry is ok.
